export const galeryList = [
  {
    id: "1",
    title: "House of Flame and Shadow",
    image: "https://m.media-amazon.com/images/I/91JjndepsqL._AC_UY218_.jpg",
    price: 6200,
    author: "Sarah J. Maas",
  },
  {
    id: "2",
    title: "Iron Flame",
    image: "https://m.media-amazon.com/images/I/91KNqG-9GJL._AC_UY218_.jpg",
    price: 8200,
    author: "Rebeca Yarros",
  },
  {
    id: "3",
    title: "My Name is Barbara",
    image: "https://m.media-amazon.com/images/I/71musw9bJWL._AC_UY218_.jpg",
    price: 7300,
    author: "Barbara Streisand",
  },
  {
    id: "4",
    title: "The Psychology of Money",
    image: "https://m.media-amazon.com/images/I/71TRUbzcvaL._AC_UY218_.jpg",
    price: 8200,
    author: "Morgan House",
  },
  {
    id: "5",
    title: "Fourth Wing",
    image: "https://m.media-amazon.com/images/I/916yn8j199L._AC_UY218_.jpg",
    price: 6500,
    author: "Rebeca Yarros",
  },
  {
    id: "6",
    title: "Bright YOUNG WOMAN",
    image: "https://m.media-amazon.com/images/I/715kbr8ZTbL._AC_UY218_.jpg",
    price: 9000,
    author: "Freida Mc Faden",
  },
  {
    id: "7",
    title: "Lessons in Chemistry",
    image: "https://m.media-amazon.com/images/I/71LhoJDfaTL._AC_UY218_.jpg",
    price: 8700,
    author: "Bonnie Garms",
  },
  {
    id: "8",
    title: "La hipotesis del amor",
    image: "https://m.media-amazon.com/images/I/61b9eQCzb+L._AC_UY218_.jpg",
    price: 6300,
    author: "Ali Hazelwood",
  },
  {
    id: "9",
    title: "Prequel",
    image: "https://m.media-amazon.com/images/I/91yhR+JP5RL._AC_UY218_.jpg",
    price: 8200,
    author: "Rachel Maddow",
  },
  {
    id: "10",
    title: "If It Bleeds",
    image: "https://m.media-amazon.com/images/I/61WmEVBdWAL._AC_UY218_.jpg",
    price: 7500,
    author: "Sarah J. Maas",
  },
  {
    id: "11",
    title: "If It Bleeds",
    image: "https://m.media-amazon.com/images/I/81yQo6uoLPL._AC_UY218_.jpg",
    price: 6300,
    author: "Stephen King",
  },
  {
    id: "12",
    title: "Blaze",
    image: "https://m.media-amazon.com/images/I/71o29imQpCL._AC_UY218_.jpg",
    price: 8100,
    author: "Stephen King",
  },
  {
    id: "13",
    title: "Sisters Creek",
    image: "https://m.media-amazon.com/images/I/812gMq1f3HL._AC_UY218_.jpg",
    price: 7200,
    author: "Lee Anderson",
  },
  {
    id: "14",
    title: "Twice a Bridge",
    image: "https://m.media-amazon.com/images/I/61yDh-RzKAL._AC_UY218_.jpg",
    price: 6300,
    author: "Mona Hodson",
  },
  {
    id: "15",
    title: "Bright Young Women",
    image: "https://m.media-amazon.com/images/I/71loRRZzhqL._AC_UY218_.jpg",
    price: 8300,
    author: "Jessica Knoll",
  },
  {
    id: "16",
    title: "Ensayo sobre la ceguera",
    image: "https://m.media-amazon.com/images/I/410xJ3e-3aL._AC_UY218_.jpg",
    price: 599.99,
    author: "Jose Saramago",
  },
  {
    id: "17",
    title: "La armadura de la luz",
    image: "https://m.media-amazon.com/images/I/91UW8ps9opL._AC_UY218_.jpg",
    price: 799.99,
    author: "Ken Follet",
  },
  {
    id: "18",
    title: "La biblioteca de fuego",
    image: "https://m.media-amazon.com/images/I/914YfLalvQL._AC_UY218_.jpg",
    price: 899.99,
    author: "Maria Zaragoza",
  },
  {
    id: "19",
    title: "La sombra del viento",
    image: "https://m.media-amazon.com/images/I/61zOWUcvMbL._AC_UY218_.jpg",
    price: 1099.99,
    author: "Carlos Ruiz",
  },
];
