import { Inter } from "next/font/google";
import "./globals.css";
import { CardProvider } from "./component/CardContext";
<<<<<<< HEAD
import Barra from "./component/Barra"
import Navbar from "./component/Navbar";
import NavbarRespo from "./component/NavbarRespo";
=======
import Barra from "./component/Barra";
import Navbar from "./component/navbar";
>>>>>>> dev

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Proyecto Libreria",
  description: "Generated by Romero, Vaserman, Egaña",
};

export default function RootLayout({ children }) {
  return (
    <CardProvider>
      <html lang="en">
        <body className={inter.className}>
          <Barra />

          {/* <Navbar /> */}

  <Navbar />  
      
          {children}</body>
      </html>
    </CardProvider>
  );
}
