import { Inter } from "next/font/google";
import "./globals.css";
import Barra from "./component/barra";
import Navbar from "./component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Proyecto Libreria",
  description: "Generated by Romero, Vaserman, Scaltritti, Egaña",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Barra />
      <Navbar />


        {children}</body>
    </html>
  );
}
